apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
    - bitnami.yaml
    - grafana.yaml
    - kured.yaml
    - linkerd.yaml
    - prometheus.yaml
    - workload-charts.yaml
