apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: linkerd
    namespace: linkerd
spec:
    releaseName: linkerd
    interval: 10m0s
    chart:
        spec:
            chart: linkerd2
            sourceRef:
                kind: HelmRepository
                name: linkerd
                namespace: flux-system
            version: "2.9.4" # TODO: upgrade to 2.10.2
    timeout: 30m0s
    install:
        remediation:
            retries: 3
    valuesFrom:
        - kind: Secret
          name: linkerd-certs
          valuesKey: ca.crt
          targetPath: global.identityTrustAnchorsPEM
        - kind: Secret
          name: linkerd-certs
          valuesKey: issuer.crt
          targetPath: identity.issuer.tls.crtPEM
        - kind: Secret
          name: linkerd-certs
          valuesKey: issuer.key
          targetPath: identity.issuer.tls.keyPEM
    values:
        installNamespace: false
        identity:
            issuer:
                crtExpiry: "2031-05-16T19:54:59Z"
