apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
    - release.yaml
configMapGenerator:
    - name: kured-values
      files:
          - values.yaml=values.yaml
configurations:
    - kustomizeconfig.yaml
