apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
    - namespace.yaml
    - release.yaml
configMapGenerator:
    - name: prometheus-values
      files:
          - values.yaml=values.yaml
configurations:
    - kustomizeconfig.yaml
