adminUser: ops
alertmanager:
    persistentVolume:
        enabled: false
server:
    global:
        scrape_interval: 10s
    persistentVolume:
        enabled: false
nodeExporter:
    hostRootfs: false
