apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: vault
    namespace: vault
spec:
    releaseName: vault
    chart:
        spec:
            chart: vault
            sourceRef:
                kind: HelmRepository
                name: hashicorp
                namespace: flux-system
            version: "0.6.0"
    interval: 1h0m0s
    install:
        remediation:
            retries: 4
    values:
        global:
            enabled: true

        # This deploys the UI and surfaces it as an internal service.
        # See out-of-band Contour ingress definition for external access.
        ui:
            enabled: true

        server:
            # This configures the Vault Statefulset to create a PVC for audit logs.
            # See https://www.vaultproject.io/docs/audit/index.html to know more
            auditStorage:
                enabled: true

            # These Resource Limits the recommended node requirements in the
            # Vault Reference Architecture for a Small Cluster
            resources:
                requests:
                    memory: 8Gi
                    cpu: 2000m
                limits:
                    memory: 16Gi
                    cpu: 2000m

            # For HA configuration (and because we need to manually initialize the vault),
            # we need to define custom readiness/liveness probe settings per Vault HA guide.
            readinessProbe:
                enabled: true
                path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
            livenessProbe:
                enabled: true
                path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
                initialDelaySeconds: 60

            # Turn on High Availability, use 5 replicas, and Raft for consensus across them.
            standalone:
                enabled: false

            ha:
                enabled: true
                replicas: 5
                raft:
                    enabled: true
                    setNodeId: true

                    config: |
                        ui = true
                        listener "tcp" {
                            address = "[::]:8200"
                            cluster_address = "[::]:8201"
                            tls_cert_file = "/vault/userconfig/tls-server/server.crt"
                            tls_key_file = "/vault/userconfig/tls-server/server.key"
                            tls_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
                        }

                        storage "raft" {
                            path = "/vault/data"
                            retry_join {
                                leader_api_addr = "https://vault-0.vault-internal:8200"
                            }
                            retry_join {
                                leader_api_addr = "https://vault-1.vault-internal:8200"
                            }
                            retry_join {
                                leader_api_addr = "https://vault-2.vault-internal:8200"
                            }
                            retry_join {
                                leader_api_addr = "https://vault-3.vault-internal:8200"
                            }
                            retry_join {
                                leader_api_addr = "https://vault-4.vault-internal:8200"
                            }

                            autopilot {
                                cleanup_dead_servers = "true"
                                last_contact_threshold = "200ms"
                                last_contact_failure_threshold = "10m"
                                max_trailing_logs = 250000
                                min_quorum = 5
                                server_stabilization_time = "10s"
                            }

                        }

                        service_registration "kubernetes" {}

# see https://learn.hashicorp.com/tutorials/vault/getting-started-deploy#initializing-the-vault
